### ISSUE TITLE
关于 GraphDTA 应用于BindingDB数据集的代码求助

### ISSUE THREAD

**Issue by yvquanli** [lifanchen-simm/transformerCPI#1]
作者你好：
我是一名图网络基础应用的学者，我没有办法在公开的信息找到您这边的联系方式。
最近我打算做一个亲和力预测的一个工作，应用我的基础图网络到亲和力预测体系。
所以想请求一份 GraphDTA应用于 BindingDB的代码，感激不尽，很希望能够一块合作。
希望能够获得您这边的代码到我的邮箱：yvquan.li@gmail.com

**Comment by lifanchen-simm** [comment]
已发送到你的邮箱，希望能有帮助。

**Comment by yvquanli** [comment]
感谢感谢

**Comment by yvquanli** [comment]
感谢哈哈，如果最后跑出来结果可以的话，希望能够加上你的名字在作者列表里面

lifanchen-simm <notifications@github.com> 于2020年8月6日周四 下午1:57写道：
