### ISSUE TITLE
he result of his reproduction of the original text is inconsistent with the original text

### ISSUE THREAD

**Issue by czjczj** [lifanchen-simm/transformerCPI#3]

**Comment by czjczj** [comment]
The result on the kinase dataset is not as high as indicated in the article.We have reproduced the results of the paper. The result on kinase is only 0.55(AUC), 0.22(AUPR)

**Comment by lifanchen-simm** [comment]
GPCR集上训练的模型和Kinase集上训练的模型已经上传了。
