### ISSUE TITLE
对于文中给出的在Human,C.elegans上的结果的一些问题

### ISSUE THREAD

**Issue by czjczj** [lifanchen-simm/transformerCPI#4]
对于文中给出在Human, C.elegans上的结果，自己按照您的代码复现了结果，其中在Human上的结果AUC仅在0.92左右，C.elegans仅仅在0.93左右
![image](https://user-images.githubusercontent.com/32976401/96818753-a56b1980-1454-11eb-87c8-1fae6dc46d97.png)
所以对于您们的代码，能够给出一些运行条件的解释，或者提供这些结果的说明？

**Comment by lifanchen-simm** [comment]
C.elegans 的超参数为：AUCs--lr=1e-3,dropout=0.1,weight_decay=5e-4,kernel=5,n_layer=3,batch=64,decay_interval=5

**Comment by lifanchen-simm** [comment]
[AUCs--lr=1e-3,dropout=0.1,weight_decay=1e-4,kernel=5,n_layer=3,batch=64,decay_interval=5,2.txt](https://github.com/lifanchen-simm/transformerCPI/files/5419868/AUCs--lr.1e-3.dropout.0.1.weight_decay.1e-4.kernel.5.n_layer.3.batch.64.decay_interval.5.2.txt)

**Comment by lifanchen-simm** [comment]
Human 的超参数为：AUCs--lr=1e-3,dropout=0.1,weight_decay=1e-4,kernel=5,n_layer=3,batch=64,decay_interval=5

**Comment by lifanchen-simm** [comment]
[AUCs--lr=1e-3,dropout=0.1,weight_decay=1e-4,kernel=5,n_layer=3,batch=64,decay_interval=5,3.txt](https://github.com/lifanchen-simm/transformerCPI/files/5419885/AUCs--lr.1e-3.dropout.0.1.weight_decay.1e-4.kernel.5.n_layer.3.batch.64.decay_interval.5.3.txt)

**Comment by lifanchen-simm** [comment]
文章中给的超参数是针对GPCR 和 Kinase集的。

**Comment by lifanchen-simm** [comment]
C.elegans 的超参也可以为：AUCs--lr=1e-3,dropout=0.1,weight_decay=1e-4,kernel=5,n_layer=3,batch=64

**Comment by lifanchen-simm** [comment]
[AUCs--lr=1e-3,dropout=0.1,weight_decay=1e-4,kernel=5,n_layer=3,batch=64,3.txt](https://github.com/lifanchen-simm/transformerCPI/files/5419902/AUCs--lr.1e-3.dropout.0.1.weight_decay.1e-4.kernel.5.n_layer.3.batch.64.3.txt)
