### ISSUE TITLE
对于提供的 trained_model.zip中的文件中的问题？

### ISSUE THREAD

**Issue by czjczj** [lifanchen-simm/transformerCPI#5]
您好，请问下我解压了 trained_model.zip中提供的你们训练好的模型，出现了两个问题：
（1）使用您们代码中提供的 GPCR 网络结构， 加载解压文件夹中的 GPCR_trained.pt 权重，报错为：
“ModuleNotFoundError: No module named 'model_v3'”

（2）加载加载解压文件夹中的 Kinase.pt 权重, 在Kinase测试集上的结果得到为： 
![image](https://user-images.githubusercontent.com/32976401/96845545-61433d80-1483-11eb-816c-c32e28cfcf27.png)
这个结果与原文中Kinase上的结果在AUPR上相差2个百分点

**Comment by lifanchen-simm** [comment]
模型代码优化了，有一些修改，因此结果没有完全还原文中的结果。GPCR模型我再去找一下。
