### ISSUE TITLE
对于Train_details/BindingDB/lr=1e-4,dropout=0.2,weight_decay=1e-4,kernel=7,n_layer=3,batch=64.pt 的 BindingDB问题？

### ISSUE THREAD

**Issue by czjczj** [lifanchen-simm/transformerCPI#7]
如问题所示，使用该BindingDB提供的预训练权重加载模型遇到了如下图问题？

![image](https://user-images.githubusercontent.com/32976401/97125398-c7bfa880-176e-11eb-9b51-8dcfea45acc6.png)

错误提示 预训练权重的部分参数无法加载。
请问能够提供 BindingDB 模型的 神经网络结构代码，谢谢。

**Comment by lifanchen-simm** [comment]
网络结构已上传
