### ISSUE TITLE
对于BindingDB数据集上运行结果的一些问题？

### ISSUE THREAD

**Issue by czjczj** [lifanchen-simm/transformerCPI#8]
亲爱的作者您好，您提供了一份非常详细的TransformCPI方法的论文，代码中包含了论文提到的所有数据集的细节。但是这里我在处理BindingDB数据集的时候遇到了下面的问题：

1. 您提供的代码中没有给出BindingDB的神经网络结构。
2. 本文中自己按照 Human/Celegans的网络结构复现 BindingDB数据集，并且按照 Train_details文件夹下的BindingDB设置了参数。
但是得到了一个和您原文更差的实验结果（原文结果为AUC:0.951, AUPR:0.949），并且也与 Train_details/BindingDB 文件夹下的 训练记录相差较多。
![image](https://user-images.githubusercontent.com/32976401/97401512-e6b76980-192b-11eb-82f4-da41e9ae9dc1.png)

对于这些问题，请您能够给出建设性的意见，提供BindingDB数据集和方法的详细信息？

**Comment by lifanchen-simm** [comment]
网络结构已上传
