### ISSUE TITLE
您好对于您提供关于 Kinase 代码的问题？

### ISSUE THREAD

**Issue by czjczj** [lifanchen-simm/transformerCPI#9]
关于您在 transformerCPI/Train_details 提供的 Kinase 预训练模型名称（如图）
![image](https://user-images.githubusercontent.com/32976401/98750800-cc848d80-23f9-11eb-9574-066d8ba991bb.png)
和您在 transformerCPI/Kinase/main.py 填写的模型名称(如图)
![image](https://user-images.githubusercontent.com/32976401/98751602-5ed96100-23fb-11eb-9cc9-11d3230955d4.png)

无法相互对应，判断可能没有提供有效的 训练代码。

这种无法对应通过运行您的源代码得到了验证。

通过运行您提供的 transformerCPI/Kinase/main.py 的源代码，自己遇到了几个问题。
① 随着训练的进行，在Kinase数据集上 的 验证集 AUC, AUPR呈现上升趋势，但是 在 测试集上 的AUC, AUPR 一路呈现下降趋势。
验证集：
![image](https://user-images.githubusercontent.com/32976401/98751281-c9d66800-23fa-11eb-8adc-3f34ff39a045.png)
测试集
![image](https://user-images.githubusercontent.com/32976401/98751351-f25e6200-23fa-11eb-9f79-f6090b7b9d07.png)

因此想请教 您是否遇到这个问题， 如果有 如何 判断模型训练的终止情况的？ 【感谢】

**Comment by xmhh** [comment]
![image](https://user-images.githubusercontent.com/42038757/125100725-008c8b80-e10c-11eb-8cf8-de3c7660912a.png)
请问您有遇到#无法加载成二进制文件的错误吗？

**Comment by xmhh** [comment]
您这个训练这么快的嘛。30s一个epoch吗 我这便得20多分钟
